server.port: 8080

logging.level.ch.dickinson: DEBUG

# needs to be a single-line comma-separated string.
websocket.additional-allowed-origins: >
    http://127.0.0.1:${server.port},
    http://localhost:5173,
    http://127.0.0.1:5173

headless: true