server.port: 8080

logging.level.ch.dickinson: DEBUG

# needs to be a single-line comma-separated string.
websocket.additional-allowed-origins: >
    http://localhost:9000,
    http://127.0.0.1:8080,
    https://add-your-personal-codespaces-url-here.preview.app.github.dev
